on: [push, pull_request, merge_group]

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Poetry and PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: |
        pdm install --dev
    - name: Lint
      if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
      run: |
        pdm run lint
    - name: Run tests
      run: |
        pdm run test --exitfirst
        pdm run doc-test
    - name: Check links
      continue-on-error: true
      run: |
        pdm run doc-linkck

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/p/smolarith
    permissions:
      id-token: write
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # https://github.com/pypa/build/issues/745
    - name: Build package
      run: |
        pip install build==1.0.3 
        python -m build
    - name: Verify package metadata
      run: |
        pip install twine
        twine check dist/*
    - name: Publish package to PyPI
      if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
      uses: pypa/gh-action-pypi-publish@release/v1
    
